name: zephyr
description: zephyr by claret

publish_to: 'none' 

version: 2.2.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  http: 
  dynamic_color:
  geolocator: 
  geocoding: 
  home_widget:
  url_launcher: 
  intl: 
  battery_optimization_helper: 
  animations: 
  fl_chart: 
  percent_indicator: 
  flutter_colorpicker:  
  json_annotation: 
  workmanager:
  flutter_local_notifications: 
  timezone: 
  permission_handler: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  json_serializable: 
  build_runner: 

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/zephyr.png